### ISSUE TITLE
Error Atttempting to Run Latest Build

### ISSUE THREAD

**Issue by hparks01** [mmguero/zeek-docker#1]
Receiving the following fatal error when attempting to run both latest and custom build of zeek-docker... Failed to load library "opt/zeek/lib/zeek/plugins/packages/spicy-http/http.hlto": /opt/zeek/lib/zeek/plugins/packages/spicy-http/http.hlto: undefined symbol: _ZTIN6spicy2rt9SinkErrorE

**Comment by mmguero** [comment]
Yeah, that is due to this issue: zeek/zeek#3177. I'm hoping they get it fixed soon and a patch out. Some spicy-based parsers are missing symbols in Zeek with the 6.0 release.

**Comment by mmguero** [comment]
Temporarily reverted to v5.2.2, when Zeek 6.0.1 is out I will update it with the fix and close this.
