### ISSUE TITLE
Error when building my own docker from the Dockerfile.clang

### ISSUE THREAD

**Issue by unkafunka** [mmguero/zeek-docker#2]
failed to load library "/opt/zeek/lib/zeek/plugins/packages/spicy-zip/archive.hlto": /opt/zeek/lib/zeek/plugins/packages/spicy-zip/archive.hlto: undefined symbol: _ZN5spicy2rt6base646Stream6finishEv

Build using master branch and this docker build command:
docker build -t zeek-local -f Dockerfile.clang .

Run using:
 sudo docker run --network host  --cap-add=NET_ADMIN --cap-add=NET_RAW --cap-add=IPC_LOCK  zeek-local  zeekcap -i en0 local

Build OS:
Ubuntu 22.04 full patched.

**Comment by unkafunka** [comment]
if i build from source it runs properly

**Comment by mmguero** [comment]
It is due to this bug: https://github.com/zeek/zeek/issues/3177

When that is fixed, my container will be able to use the regular release debs.
